name = "UrbanEpis"
uuid = "5c923179-0abf-4395-bdf0-7873af48edb4"
authors = ["Fabio Mazza"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GraphEpidemics = "6aca1ccc-3d4c-4aa2-bef3-7b7b4d8fa495"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
SparseArrays = "1.11"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
